language: python
services:
  - docker
python:
  - "3.7"
addons:
  apt:
    packages:
      - docker-ce
install:
  - make install
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose up -d
script:
  - make test
  - make test.integration
after_script:
  - docker-compose down