if: branch IN (development, master)
language: python
services:
  - docker
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - make install
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - make test